package Easy;

public class BasicSearchQuery {
    public static void search_query(String[] query, String[] pages) {
    	int count = 0;
        
    	for(String page : pages) {
    		boolean match = true;
    		for(String queryToken : query) {
    			if(page.contains(queryToken)) {
    				continue;
    			}
                match = false;
                break;
    		}
    		if(match) {
    			//the page matches all words
    			count ++;
    		}    		
    	}
    	System.out.println(count);        
    }
	public static void main(String[] args) {

		String[] query = {"funny", "joke"};
		String[] pages = {"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about joke new products and services available to funny the Italian market.",
"dsuitNes ealn oasv itmo0e e.mayeltIdtagcetiyrvu rt,0rateenreinE    iiewusuaw0vi prec fpe  sni0aaeoesIe  aoyecIll iiltoelsaarettI Naoaatl lod dhhIc  lvaaled nIrathe g1e ee ogs ib,rI0aa9t ,s tr siintis n noIss ent a bE roig swnraa ye doecl su evrimsi lnsh0 ewtewd c.harn,Iatbcdmetawn datnsbatsknekitp upbrasNhalt  tpiin dteh sdEsl sba  r1asp4al  ln ia2sea g.mtesulebn",
"EeppeuetIeu a dii dgtel  bdt0bawh I apweps,ts0led0tch,eraltp l s la9lachnnhncooer fn.a nrt1t s alIitalaea a ra oeIitiot sdneI m hli rl tid eyselI nson d nvas  ,vcatydsese paekh a i  1rilbenu .l ibE ryariao,buledreitsoelto4tviawseta imisdu2 ntelrw ean ks tca gleyIguN rese ioiisgeawItnmsscmn oensm.t sttb   cEisavsaats oe0anaaatngnI NNhv r0d0ueaireweebs rri  satase ",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available joke on the Italian market. In funny 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services funny available to the joke Italian market.",
"nivkelris  aoi0lIeaeisah nr seoewutinnc0 lbieae igsaIa0ibe,ElsgerIclyalm e1mNv cho di.oldbdepsui vt aaa tss newctgdmlye   p bnla wsse .rllut      2etnI0a acecsynslirea,settsean a  t ps0 gsdt tdiehrwen 4do1gul naI beseIwoErti si  i tf raEi Na.t tbslap  uo wtuh  IeahItset0, rnaiadtanapd tosne tlnriroiaese shei snea9dvtaitnmaabv asrNptlaaautkc,r osdoIneee  rymheletr",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily funny news about new products and joke services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and funny services joke available to the Italian market.",
"10 joke times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, funny nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"dsssbomi naalseel  bob.chnIn0  teitt anteuoirtm earenaeapisi tsrsrNes i  iu lds  nseetdterrt2 4ayaNtseI1d9th 1ai etr a   iuwna0ipniktvvce pl lld Emttehy   bo md eisg,refu t g.eia u tanlwcrEnre n  lra ievamee0n,Ioatl tdago.ke aane lrw Nl es hcssseabac listaI,ocw vgyn pIteastrooeawals enpnsaIlbesae0tsr dnogiipy  aIls tdwI0hueahiie,estI edia l shEcvbi stnod la0aruaa",
"10 times a year, IEN Italia, provides a funny digest of joke the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and funny technologies joke available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"optcntwiiaeapvlih  Na bhb0 eeEIe e bnanIdamt terin0  sln tteI,sNidatsl dieblir etloelw at aeca1n1e roeie   deusrroifcnnl snws, twoop usmaEil  ss0ni ,rom sgd.aesen  rsul.Eaeertk  shanet sslreswpIrlehIa ysaw 4tiuo a sea.l  evamsitdcta n0laatogeg rde gI ciittrcacdst byv tda0tslhnnuvIdsi a rlu,e mIe itnd  si a0  a9  akNeeaoyoes trentglavlbnthuh spaasaeebea2iiiIayrp t",
"nEeo .l0mbeca cIagneh hlvlrbvrev mlcv rwi,,ikslanelistisiINasnn  9uI eta n  tle cnaoaedarsv 4pirnrao0  gmseu.trtsdnrswart ra NoInad   tdsliteubEnsln atN adii2ewsfartIppeleIa ud eldhoetgte e, hlassra so0sutt eeyo0a    b iiabst  snab sipncaa odhu ii eatitc oteur m.ai genyhiy a1sa to  laI ye ea wtigt tatse nep m,1dase swlpIa eltdiakeeeibrEswahns sso0ti0dl eIclteener",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with funny daily news about new products and services joke available to the Italian market.",
" h. rgga1I sttnsliocpseey  lltailaeawdrn betone rbas 0us0s faa  l ln0 de eu d a bbravd eisestondcad0mNbuasmc.oeelElieoat o1edsiylhsek   ee,nluaepmiosi n riat  sgEnmauiIc nupie a pgss Int nIbeattsgotInrsl esamsthape4rat ii rte,raaa0ahstwI9  ileiIy  s dewl rkerhaaa  irN2esi,ahbv e c e ny  ,tttitwdvoecvrlcidneattes n tasta hwlep e.svu0leIidtn tniIrN aa antwsorleio E",
",n0ts td ran srEioiir lrt Iabb siahlcvoam satplsIu i tdia0rlnh g4 oint oeleroersnI.behn s eu a ae0srl wigasat recnIEvw c etoah.ptIeelis aewa, taua s sn hitanwpeuw mtpidtledal i1u rN  e0u2t acI otaod tirsoEoattndyilli dseaobetmeyleaIc ,db p9teaete esysdeN eein Iretwk snl a eksfsmve  ped e,en 0reu vtshcss lav rbninbaeriaNl1eim idacsasaetg In0sa n   g.glaystant ilha",
"een naasdtc e0au Il a   sl m oiacwbe.gstanah vi tIca 0epsiieeo lineiai 0e,ro Eht roe4 htt E  esunuhl trsi Iraaebe veo ulpnwstadt.tams eaory dsvbarlasle olb iurmlrlskngp erssaytidadotaI ,ba i g sintrttah cn ctfvhid alerbwpytsdon   l aleIpe ,c,seos NeE daseIIailuo1I eneNmateIentaemarnactt ks ywdipana rnnwgtaidansnte9  rN0 svu wlae segt 0elitis1 2t bsi0 rdlshiseee.i",
"IhlimscaI saehae,idroeep stpk N treeeae0easw das h rnms saie  neoese2 oda 0aeplnle vty 0omiltd  nawtru ge,eso t vtrntatutaa pEeresrtansate abs uly1 ehdgs in    b0tlecIteapolIwescdbttilc  we tIuiva4nfadEaIouah0ni.dblwsiesceI astaaedrtleivt sut rN 9 ii nI 1tia  i sepr l gn,imbnroinNbnd  ,las  gko .iirssionnio0lh rnyia em uIa vatsaryhrteaaeEclwasgd le  tt.nb ceslals",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available joke to funny the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers funny received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to joke the Italian market.",
"10 times a year, IEN Italia, provides a digest of the funny latest products news and technologies available on the Italian market. joke In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"meanvrssdttll4ets 0ioalealasIer eerrmigeaa N a naneawot eni,swc a  ce at  d setonIort,vg 1e0  av  tssilNesldnithdE.mo.i, ueeleNnn ea eEabe r,ihIseic0si1nget wlednppai a2ygl sodItralbnrIaitobdm eu  t tirwIih lt0.ucpslle0vh u ygnudnpdfttwsitInas  a sest rtst b0 epas siatisrn   lra oal pyaeriid ntuoaaceEs  ki hcie  bata Ieh tah sdiav wyeaskabeeralnoubreclmtIos  e9sn",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market. funny joke",
"10 times a year, IEN Italia, provides a digest of the funny latest products news and technologies available joke on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"wiIsl lruIlusenmal a En  rInl0soieie  r IoIie u  tgd ,N,r ratber ea1deb c9aasm divN e  Ias lswhtan swrsr o e sbckenaittolpweti4inan dsslt yspoyleod a  fpt i0lla,katai dar.agesIg ea0inehr.risobas eena Imvcsar0t iaot tI  ltsvgydaear eEipNtsm  a sreaniaa tw ntc  stne0lieotc eitiun eedsieciluohoy auh2wnt elaee  e s leneis,b aEhate0ubvdpntesrhndgtsshl1anaeptcbm va.dtt",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on funny the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new joke products and services available to the Italian market.",
"iaspec ghsnIwbacu  getsteIeuul1screbm,   ev ka.gtidiNrye naechtloerrbtahh rlb scdsy  ia0 e isenotrI  ahr sn domhp.emelauisneame sgaksdvetec rlanatt,eyii n, ieudwellIva l.a   odsi riaieas pN,wtwIo0ls oeaIl   wo u Ef0espnntasstt iias1trarlt e este2esansd  celea privtt hnnreaEa4lEd0IdtNntao elt ib 9ae  eolsaia nt dbi0tvapbitsm alat  Is  0 nwigrndnaai uoIoatrs yelnes",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the funny Italian joke market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In funny 2009, nearly 14 000 subscribers received IEN joke Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available joke on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers funny and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers joke and purchasing managers. IEN Italia also publishes newsletters and updates its website funny with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian joke market. In 2009, nearly 14 000 subscribers received IEN funny Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about funny new products and joke services available to the Italian market.",
"scdenI eaiataIilpIissetuealhse e srn dei0aa ivnne ivavEaee oybets  l a.icbm illapsyneae enrsvb rtEm t0ehonaecolaw0nIe  trtneo s I. grit,NbtueaaEn4esg iaa u sNutrole gws I   01tahene lse rttpneyace rNndtdaaewaul uobt2f wot pord m iaiasnh,  tnsvl tsta0ideatrsI,dscgtoast 0eetaan nawtlrtsie1  dr.i driuie k,csrwbatlyahosI hco kl Ili ig ledn    9aip bll ssad sepismmher",
"10 times a year, IEN Italia, provides a digest of the latest funny products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with joke daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to funny the Italian joke market.",
" btgi cetlaa ate tt.tea  hda no lusd iwo ,tsedautkn wasa0sumstey0Ia nemnE9srhccp,aItpes  IrraiubaInslvl mrhpnot t ellrbosea enetvblIlr iidennb lt ru  rer1Io nivt im1et b0liwsiwthtecewg iI Isasnt pag lEtnalEehea ed,i usel 0aaeI blpo  .snishmt  asetnsN2otei y eieldirv seerre.no h0siaeifdope vwd Nk useette drla iey4asc  0gaasiaa eiassa anN ots,sondgac   aanylrarcd i",
"n sgalan9pIn  eleatsaleotaeiartbse p0 ntaig1t teymn e te I  ala1en,a mlnc e rbr  l ehc etEowIerstsntbeilossNe esub0oeavmtbcosi lttaatdns0iagl ksset p E 2yIesd ovneen0N,ehaadwlbhiiie .pse4 sNd0a vi  lwasaniihry ut u.raispawcolltg dviu tesud oIpu ddt nnEtkiosel aeecnn hsae,w rh diIf0rr,Irele rli ae adeacsdyitiaeis gc   rbtooi svstta r maeIirautaIa   m ln.wanast shr",
"10 times a year, IEN Italia, provides a digest of the latest joke products news and technologies available on the funny Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"w e4wka.nr iuttapnNlskIideaoru It,uehwIdhota1 ebr ce,s,onrt srIedea aen gntabas eli1 dneIytitaonles   nysg sgan0de tr boavaEsc m eus lnph .lla an  l lsor das gtstddnniassoaioir  eeaibemipc sefnt9se.waaaemNt evIsi t0 0t Eurnpriiavs2Ivbletot ataNs leeIe eIrt eii estaha sl isacn ceciEbi  h00 hdsyrrlieh laeiiaaoa   amoeu egwl dlwtbni stetevn, myprtapea tus0sc d tllr ",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates funny its joke website with daily news about new products and services available to the Italian market.",
"wo  ddsrpreaethi eaeItee4l eytswg  yltitktyv0dc 1e r d asa hsretlpil s.nenv  na.n.ubol0osbshtiIanir ao aue0 senrlstypsducel di  eo0er9ho w  h  eb1ea  tli IaedIetalhmtnE i ibasalwa  as vsent im isbagm bsdst0ee leandbdtnte trltiEttn e dwaustma eainsrimacNneft Ir lcei peonselnlha aonl ukp tsvorist,raain ,rl uea, anvpIerNIa N ,it0saew 2IieaciE  tsrcaosaaiocgsIuse gag",
" taieo i or s esEsmtaa tpns neerawnaeltetIitweIa0u0 .d. icps aIae hgg e2aheuahvaN4lIasatev0n0b augelrtuolaai rrefnti ieakss m atrn1tgr ncilsoienh dl slectnc ac oa Nia  od ree viblohaat,s eansitaoaicieiltr cvss ellrimnmne odetsldl bans ha aEtg N,e.streeeat,bldIEd me tdwsirsu 0yeeedusap  wessyptb ,rsybnpiIyntI  nItt l ld ei vko 0w deas s wt1hb ta onrre9a  npl Isiiu",
"e  uauerbitaestllndn ewatvt risvasl i wwnbIl9Npl r e ,leetnh4 aahesistt0 osesvs sEaorobtil n c   nmclobb wrIssimoess nw.esteaeamn,Erlt teslaru i 0iiaii  eeeedae losIytusalra  eIanss w l tNnngsroNEletyhih iaItupdnteIlmpa tbigethn atmpaeaa ilparardek a1a sta uol rgfncbo1 Ieedcnkc cho nopi neaesis  0rattada.ec 0riadsieyt,tegIas  e ddIi0 r2 u  g.tnthdsy va, edaie 0v ",
"mtttn. ardsi cmIia  ovd  gepnsn.sEirkor diaul, sir se ts0e tdnenn stacew  aaiae0 enE  ste1nlrssi4 oo Il o npnrbiis eety Ia pgritlr  gtwrrdielrvlsmen rh  ee10treilienwaI    tyuian s Ileias,Icnoapyeteme attNheseluahs0,sdctoesba,trssdnal  a ee  eoaloNasb utecdnel0c aaataaI90ic vhshil 2sveaaam  lwgsdupbeekelniwitwt rb.tba bpt  letaaoIohganuI  ie aEtle daasuiyNsvd tfh",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In funny 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website joke with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a funny digest of the latest products news and technologies available on the Italian market. In 2009, joke nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly funny engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new joke products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available funny to the Italian joke market.",
"10 times a year, IEN Italia, provides a digest of the latest products news funny and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available joke to the Italian market.",
" tn0hb eii1eue nedshIa ghvI  ilra  s arI,0 rcrlehes0 bset,deashilnol wne0wc  tInav cadgttspweansi a ynit  oeenerrigdtiht   aan moetrt yt psun llrksualuvea oI t semebateEe akl ss.oa srrusshlc 4aietugInfNsaNsneieaeoE d atpIe,.eI, dnvmplg01Ndcdsoitroianvwpei iadr o2.E ne essnssela aa ct atls btid0nlamwtiiwsia ecyastapt aeoasl ayi a u  dte bieo it9nrlleab r bt lItmre",
"g0eeedgy slrkhbe iirse cIeetriEr  b edbt4ialeawta 0.u trpis s iIusc n seeIsrihepeoiigbno,op taeawiaes,e  e,den wll sIntl1npe1 menos  tsl ocNmreahv aara0buaeiemesk su I a ada nwl r  bhiles2ptgutstgsat0 EsdlldsohIlat.ul anyattthssmnnvrno oae alt i a  hsnisttcenenfsddtyys r   ureair oact diil ep  ndaam I0toIevn9esivrl ie lnatvEtae t, waN.eal isaaocIbiradatcN ta  0wn",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the joke Italian market. funny",
",nrlua ya ei kreaeae  i mlitiwwhew 4saeto apele gn vneoeiptnt gss,lhhi 0lantesE er ebd nmE tvIIl t tdaesNec  se,ilris.aaseeutbpsrnob1esrb aaiysmhou0bt ruhraniy0dtre m  cysalc n2dl rieauaatanNcf 1ctlI  tai clv h  .anneia  o0gaa  e 09i ltaslageteIwkvsal stIodio tei d iten sals wwap Eodrtvmicn ape t e edtsranbrtiIdtnIoosruoeselnds.tlaesIsnrsui,aadseIheg ip tN sb a 0",
"chrkiee rw i0 n 1aot cn  0asoIy t bn e0 9NI aa o. aaas,us is oehoatp gv n ss vebtaetilpse0lt.sci4a ls dtawntm e.ebh grrNddaaa tobtfsi 1atedrlitenrsIlohrniEsnEinareelmnryIeeacte e,relhmidoieaoebemsse w n ges nmscuav   rral tedg dsn,tinsalapive lia aab0I eEuslsd l a rshNidssr bt, 2eaedi hkiy0pdpateo ltIa pusan  ela  aatyw tieiI ne Iet Iellvnwtittuorlgastestinw cucu",
"10 times a year, IEN funny Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market. joke",
"10 times joke a year, IEN Italia, provides a digest of the latest products news and technologies available on funny the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
",0sea ospoidsdt0aesaiur pwi iriv ara d n9sevhNauisa ariaas1n  roI hpa tciyaeese Nsm rIralinsaeksI ted a a40eentl tbEI,l  grdtNeyl  tpseh1ieles   akf   nnaositaniswbgatbtadpers daeeeclutsei  ln esnmoene l,  astlhbbcmaiensIwgllu tsvrv catgtyueiwcmaoab0 Eiidnt.il2 o Ie lv y mIweensc p w .taoll leEioieat. 0r esd gctdsh nu nhul aheebrener aIs troostitantetda0atrI,t n ",
"srkc aglbeiItn iyres0blildnaIrse e wlc ao2IneIeddnitm 9 rrlee sldulms a l eat nye b  iatrac oiaba0fo.rtesEEianaaetsnstn tIiIe0tstri  srareutcp0nmwwhmteailas1ghpalk,oha yitvtsotlog EsIt,. leh r4asa csu si uaeo dsa iueIteataitsdw s ton ts iati  rpnbee.biaha ce aucpp teaailrw peeow,b d  te    lIe,ehe nvmse a  ddanNynie  dtalnei se 0vnogleNsvslas Nthveunn rogaisd10r ",
"ea i bohacrtc  Esy IiauiNnuat d 0pe ehsotieacIspo innaakfsrslessEs se s r ayderrnaasenawls0tlasthblmns aheavlu ,co t rE aloti ewagsastaIlggi adac tNmieb tpldie  neentetasmi rl ,shperbo i o2weusebty.0v tr ln  NIdhosetitear .iIiat rhr si0 bdecdmtec aesaetl 1waiw  0vnm  uav ytsivI lieIased dtnt.tron aeItdlaieaId iensnbn, tpegnpau eeluotg wlar,nkel9l oi ee r  14 sn0a",
" tlvnsEnoag ah  b  I bpchkh idm4tap hoeaos cIerlueaIeey olnlntiesretcou  ku  2rhnrerdinwttin tetniavv tpa tmEsur sbubc.es drnl INaaIse sr  aa.uslers e.insd irmasaara aa tlynr  sl,sb ch,tttaon1t0Eetreeeis iws tIasvang 0etitpunasevdetwa l 1 0ws 00pelaordaNitsletby ds re g  aaa9w lnlmi c e imiInitea0oescealagepnoessgIeaty b ,i h oInNdoei tswe leiif ,deeidail d alsta",
"lll tnddnrav   esuIe  a d0a rkrieyIb1r0nsnifdhtNtaasas bImnr a grvnswrr slEeanta hi  Iaasepep ee2esla amm nrick,or0oasnmaeaaeyaiow Eeirieun  t0a Nlt1le  nubneiIeieaale.dote atnsiu spasywnitt aaavitct dnci tthiIsr. cnl gess ctslvdod dsIoewtbv aaeuaw adIo ia,dnttr0phe9cIen  lr bail  os0ioutlet sileyclE smtaauts t N ret hiee sigeps l ,h  seb,wghlttgiee b 4eoosp e. s",
" awal  h ageno   Nsanst.nrpngo0eaar Nm aaecb0c s tytphlrdebtei ciene ealloes m.aEbuekoit cni1shiis t 0edu0t uaev,a, i 1e etlc0gyptir4 thpsartoaelvdatads s wgstt tbn ersrdenn mseka olIeeeIu ulnieitby aIs ern rldi rnrua.to al s2d oiitssnal Nssfpiru eoinIl ab 0awe wa9astdw wta nlnl tamodi eie echIadaemst vpaen oa IsIh nelvsEel t Ieaia dgy I btrtiasclr,hse,s ietvEirs",
"10 times a year, IEN Italia, provides a digest of the latest products news and joke technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, funny mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"dit ctpt iIeatnnt de buleu2aia  viursIei0ds  giar Eaera onh dtelaesossvl a aeneast aehyo ta , i1te v li b4.Ifnt saw0eis.pcrIot ltnrmolpratw  .ulnedrImoahiva cae,a lgd 1itNba unh soaneleEiv nd celm ssgrer   lIbpse,alsusdw0teoNekemibiealcserrene aa,N eeaeatliaEetr aiwt tss0sed bpcwtnm 9l iwynrsyk tIayag diag isIscttsh lusn ssa sntt oelnadtho0baionrp nre 0 i eeI  h ",
"i0scueii  cagvnscdnIdinatoc de ue sianltuE onontnycegw u9t esa te ty1t vds anm urhptailrbaheai01 ealiIarta bbrh tualsl tr liairlsweodehaad ,NeInradk,mcctoEr  e0oawoa0tnesessdteiEae s tt,  nsppoyrbIeisI ,i lw ap slnlaaressavea ly2 nmeatb l4rgotda sa l nt Nesrpka.na m.eetbapidreesli gIv0at ft   ebevtdiI  hse0I ioina seatiNleen Ir  e nh i toislss ahg  ewltes. rmuswe",
"10 times a year, IEN Italia, provides funny a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services joke available to the Italian market.",
"tataai9tl  ied0e.o   ar0t theatglIvovctplnceoetn1doal 0gt d  darpecsN edar kesomueria mbhvi gtmrw,sh og aI1yani etan eeisesI,ienwusataaI rawtesitnI ,nnouaIbmiIyle l ea aulelIt  heame  nestae en utnoandi tNtslnlus.cc rdatyie rifs0liabk r Es btpstachne  uissrpNs ese iswre  lasopsarlelviaait  , d es42h e snvgs h dab l0eoInbiyrsei0saw awtdnet cl E naa.sbtlEdoi  rprie",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers funny and purchasing managers. IEN Italia joke also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"oes tpts tiridmuel alE tt0,sostdeg dwIres acde eunainc tr gs nsnaedtimleeei tup ivcseNsttav9l diwt1ddkbasp   I te4l slmt o fmsanit ,e eor rr rrt  ees aNo aewnt noianeeasaiomoin.a,ii tlrot e hebIllae2.rudliade ci Ihnasie0e0oE0t1secyab yapyi b  sleeeaeEleyn urnahsa0viIuatss ivlerrcwlhstn rw Igses hNavl a  t bn  gncwa i eieraaaa.btoI snknbslhaapn as0hu ttg  apIld,aI",
"hitreeul,I eteIabrI . Nte dohwet e  ew0Eee2t gs,kee  emimvctaIeyIe0bcrl,ue,de0ledrac sba sotsa slvn rr sueltmihsttduItips  elis t agmbcsdlw   lanuedybiatc 1eiavtigngleiwi uihsant antl0n1noyevalacslnah tpp r  er sersatc odb b Io na ssitofsne dt.golsyoasiv imanarekItre ne NanIlteahpa si eo0nN daatp wi aaa saeo4staslwi a  asidnEantr9ipr d l . hsiaa  rnrtiu sEen0e lo",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also funny publishes newsletters and updates its website with daily news about new joke products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing joke managers. funny IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, funny mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the joke Italian market.",
" o c tl ih al0aadsabtussl  tpe l si.i ic0Ipiae ceem a rrshs trriars  kwn oelEcuagsei t0h ilk  td.pnnttN Ieoeattbsn i tldaeob tgl0rgdoer oenas snIwiaau,b eo n0auiet e  h Nt0tlae4p1amslw9h st advIsaswu,ps tn Eld Nebe aaIde ianInsaaaeettoar i caer dvsetie lesscbay2dygs s.sfIIaearwp arbadrcnanma ta1hlgmvrvEetsy vtie ,ihleintiyi  t nnwrelldeoeoertnneun   osi,elIm euis",
"nasinv 4t  onrye daiugwa p resp lsem ch i raetwN.oIdoa taaI   a  n taat usbt  iwrreE mlnoy  nedon iIs ee0ds,rEdsorc er0 sn  lenatsswmuoe.enef bs uatls iNaegtiitluse dlv1rNcs,akhealpdec eedtaacasaeIloghvIiipIsrrbe nrbawceg0lti taipdm  nlesIlise  apctEa at yn tei02dnh0ldtlsmikw.atn ha tssoaaoile bsy t,aaltsa eg nb  niute,nt 9shieeases1 Ite rvhtviarretIbu eoilial e0",
"l rdcI vsets aes, ee  ctw tEvedabsesnnweanashtrml rNseieoreissp  otgtIyoErwNl a0 dnn0ar iInshaph,we ati.nsbbyauularaomidmEdgeeoIg attsnestml 1 lioIud ss 2,g  gceao.dd.rh0rieeesar tu atvepuo   i1nee ,  iclaal Nnla ak0tul sltiaotaysaneeoe eIt uiwa tplawresi 0a brrt a sdtd l kia aat s nl ncIblfeseaitnItlrir  ohi0nv9 etssdipaetn iel   aai hsimyIbt ect hvs nb4aeincpee",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. funny In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its joke website with daily news about new products and services available to the Italian market.",
"tp invdtwaclse,esbo abst  purmoe rytftoiI.csinn  nI Eacraas dtut N tn bnNsI e,lertaelwoIaeh hc. Iren.teeiuishe a0e  yo seaudsesgadteuamk  iwi,astmylabtr  abcd eecclada ttbikaae0 peoggiea lsae  eist gsyir  alitt4nhe 0a2attiilvonemEalnets sIsthavpi debilsirnwsw0iaa9 wrnEr d  arv enl 1 tehreeeap0sdsrr  ssemlessalin oe ua0vpig  dI l1n thaooln,ultI   d s rlaan NetoniI",
"snlecbdI eeeu0fsroltt s t  lohtte.EbipIcsIEhhos  vui aeistatwkniw enl rdeNttsieyw nut4ghetcr apaldi s.n  rsl evaasan ryed0cs,e eshhbetiiiao atsia rllsl e s 9 aeig0 vwsp   sIta soit olbeat1ai  ree1etpali baaatle0 brna,nIe iroIgmgtee rrmrtnaninasd tIoks2t0Nu u  l0tld wto.iNwseyisamnatedE,aarei e,s  dIolynIa eusgaacaml e rida  puvdi esphn va   odabmtns  lreeaneacnnc",
"10 times a year, IEN Italia, provides a digest of the latest products funny news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received joke IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"asbeeemils n.nesaIchfae 1  ah ao rhektIo alrraicbenN aau,lle mapnein alabrttsaip tyd sndsvlema o,elgdec1sn n0 le eal0 nse u ast0alaidpmaa irtrn u2sg notNitieu ltw oe ei eto4b0ed atdcgn lr wn elo aI pitrv  yr t.It niisrgact Iteshwhu eow vtebapasllm saodlhte aaorda distiiyastvsesrs,cne9lceo eu r. I p NtI 0tiwIdert   sseiis0i atsdgsIer iet eyEnt nEa bhnEw,skavieaubs",
"td0t e 2Ilatel Noutsgaasuaeicyudtiitsrnaa ss i0swsthsIan vrEemgit  ie  incsmamrkdaeacmcwnpii0setaltNuhro etyeIpieI etn,talar us , gs. elntdo,bm aceaIp lai thvglahi nnw e0ha vn.eeelaets tbde0a rdri i duod vIee  taosE ci9enl,erae yawnst1  aoi  serpss Iknrstsaldvras bcaen4  etltf 0sbelpy  oeb tlp a adaoi irenEatsIrils lewe1se l rad lgeeINw baibt nano snot.nho  h iur",
"10 times a joke year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about new products and services funny available to the Italian market.",
"a irtpdraraooonisfosuhdEivn,psdiia2tnead.sbrethat0 sas reiam tc.yda ctp.e a1s idawisgnena h snbee r tl ealakleeIamnaNdaltpt  e I rlctla o     atrtsytns  n,a ytn0e a10slubud ,b sbi iaeno  gwithocii ravrteu0  Et trtiwat9oe rbeeawewel  hllIisg etl i eie uIer asolei s0 nnsp sleccps wrss  kr tIelaatcIneIvvnEa  hisadNoeIae  tdteslhae,imamly4essen nlaondtvieeubNI m0uggs",
"nranbil i ldoa0ttol  wat reapetc0 ioEotbn siha a r ut oilntedN,de ahs p.aetu0keg 0lInwal lsalns e at dusdllIrahcgnu cibb npsnasraIshs1udtearseoelascserauEywe2iiyo,ataiEttosie etld sisawelvt  e eretnmIb iNtts mera db 1a n pdiwe ac sane Iyet  itc levfal iiiII gre,tiae hwvt gnNeo   a e oemssshte0r0gtib v.aineul r4d asI enaeednrk perycsspon ahs ia vaItmstlm,e rn.s 9a",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. funny In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with daily news about joke new products and services available to the Italian market.",
"psn,adnreana ebmt0slbuhdabwolt0weart i seNnsttaIil i a Inta1Ieeg esslttr slodeaa...  eoipes0eusii  o Nigiitocimnlbhpas  tvnd    tn yfl I s uderi tlopeny at et  ae lgta rdesIInite gtdt mn9yarolmvsesrrEebhse0sinb nav wetyailrtiaeeea,h ee In luivo soalll0d atii0,glInhtpdhea,nErapE waaNe  o    ia1wvsaeucaeaacia thrwe e ssrlek astei kdrs2 4 mursoater ssnb nsuaccdct cI",
"its saawdlIe lteapNtIsIekbeaeIgtiwutcibn nNas w,eh r gin wbe t9 gali0draIvne a t0a slmt racoteo u 0g l ln deyEao   tryeut4dslhInmle1IIo1see sadsi en stn recte0 niirrtcn na2ssaesontlnreioiv aa rsvslwrda 0l leoutsbcc s e. ovpo e ts sa i,etsen arrIaetaiat esw .ad rio,, NE n tpi tlyars bee asn0ldieitaphil.nm p ubhdtthacids aagl eevEe ambalkayhsims  ua faepniieeohdtur",
"etiebN iyaa dwaa . lk aioatiislyNsig sneoi Ie4eh a nI eui elaal  aanwiden orIltmatEdvi  pshosculE  dnl0s  rnnI vcnbeeuIieeyIso   gnp,ieii epa0d0,arto ssawobltcetts.0 gea f aiaretIdrvtkaosae t1admrteEssc  le9g,r rrmlepidaeehnisepl phc w aettcgs tsn t  Nvntsaes ulrbI iaee0bsm in0ns1w maadhnit wed b a oall rsrr u2nseo nrh tvtlrI yndeael.s tssl  etcteeatth,uatsbiuaoa",
" tsaa1maptiseec eh ,litdEaen b m1 edirataetai eabliIyhpaoelukan  dIbaleu 2 srtng Erip0siue t9eoyimi 4s ttalcs reossdrlalnlltnralsorg  mnndi d 0NNIaupser  isbde,bidw erars  ge0o osItleNa  etthoh,ovgitse,saa ob   aEeie sdwwsvticlt ef leewaawwenemctra0. uts sran i e.Iarspt s evsgssieabinlys nn p e a I toe  ne0Iacv tathncti IecluIni thdsnyavrkaou0aael   l editn.htrna",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates its website with funny daily news about new products and services available to joke the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes funny newsletters and updates its website joke with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides funny a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates joke its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. joke In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN funny Italia also publishes newsletters and updates its website with daily news about new products and services available to the Italian market.",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and funny updates its website with joke daily news about new products and services available to the Italian market.",
"tibtg .nhltdIlNee.tllrnehsiteIoeldwc  mgeidsreIseIaaIcs at,rvr ee s pdipav lttt   b 0wah  eym ee0utsyo rtn hdganesIl rlriaolc ise 0iyea v,saiipeeEbb1bsl2nis niivrkct0sd weia  meaiw detaesi  NeIwarg9hNd ngEs motnusdv rttloh e tt  o0birrauhayeuaaetb us,aansopacat akdiIsr rele nlenl  eno nociseu  ,se tu etssaioaal4as1e0adsalnan pa pn  atcrn n .iaEtatasIwlito em  sf ",
"   niaoarElispysa ber s w h aEs  vbtese de 0Nrseo9sincidsssenEa pvoa nssolIalnaitapeaelt0nsw.esnlci  tl m sapinet4 geapllnaro,Iswaairodtod eIcggvyteue0i nme n aeio,ov e.etdarlerdsc euu b2tcisd b   ts. a,iaaualllea eot lp yitltrk  tde c aboat,ah ariu1neNr  s dsNi1ybauhe Im rhr ih tu wIttea0lnhlktgattde  ha0nc IeeIe  isw  mnisitv trbrnranietetgl0sdatwmsfisIeeIen aa",
"10 times a year, IEN Italia, provides a digest of the latest products news and technologies available on the Italian market. In 2009, nearly 14 000 subscribers received IEN Italia, mostly engineers and purchasing managers. IEN Italia also publishes newsletters and updates funny its website joke with daily news about new products and services available to the Italian market."};
		search_query(query, pages);

	}

}
